// بنية بيانات السيرة الذاتية + قاموس التسميات ثنائي اللغة

export interface CVEducation { degree: string; institution: string; start: string; end: string }
export interface CVWork { position: string; org: string; start: string; end: string; description?: string }
export interface CVTraining { title: string; org: string; year: string }
export interface CVLanguage { name: string; level: string }
export interface CVReference { name: string; org: string; contact: string }

export interface CVData {
  lang?: 'ar' | 'en'
  summary?: string
  title?: string // المسمّى المهني
  email?: string
  phone?: string
  education?: CVEducation[]
  work?: CVWork[]
  trainings?: CVTraining[]
  languages?: CVLanguage[]
  references?: CVReference[]
}

export const CV_LABELS = {
  ar: {
    cv: 'السيرة الذاتية',
    summary: 'نبذة تعريفية',
    education: 'التحصيل العلمي',
    skills: 'المهارات',
    work: 'الخبرة العملية',
    trainings: 'التدريبات والدورات',
    ruwadCerts: 'شهادات موثّقة من منصة رُوّاد',
    languages: 'اللغات',
    references: 'الجهات المرجعية',
    present: 'حتى الآن',
    scanToVerify: 'امسح للتحقق',
    score: 'النتيجة',
    generatedBy: 'أُنشئت عبر منصة رُوّاد — ruwaad.app',
  },
  en: {
    cv: 'Curriculum Vitae',
    summary: 'Profile',
    education: 'Education',
    skills: 'Skills',
    work: 'Work Experience',
    trainings: 'Trainings & Courses',
    ruwadCerts: 'Verified Certificates — Ruwad Platform',
    languages: 'Languages',
    references: 'References',
    present: 'Present',
    scanToVerify: 'Scan to verify',
    score: 'Score',
    generatedBy: 'Generated by Ruwad Platform — ruwaad.app',
  },
} as const

export const LANGUAGE_LEVELS = {
  ar: ['اللغة الأم', 'ممتاز', 'جيد جداً', 'جيد', 'مبتدئ'],
  en: ['Native', 'Fluent', 'Advanced', 'Intermediate', 'Beginner'],
}
